#### numpy 모듈호출

In [1]:
import numpy as np

#### array의 생성

In [2]:
#string type의 데이터를 float64 데이터 리스트로 생성
test_array = np.array(["1", "4", 5, 8], np.float64)
test_array

array([1., 4., 5., 8.])

In [3]:
type(test_array[3])

numpy.float64

In [4]:
test_array.dtype

dtype('float64')

In [5]:
test_array.shape

(4,)

#### array shape

In [6]:
vector = [1,2,3,4]
np.array(vector, int).shape

(4,)

In [7]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [8]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
         ,[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
         ,[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
         ,[[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [9]:
np.array(tensor, int).ndim

3

In [10]:
np.array(tensor, int).size

48

#### numpy dtype

In [11]:
np.array([[1,2,3],[4.5,5,6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [13]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float32).nbytes

24

In [14]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.int8).nbytes

6

In [15]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float64).nbytes

48