In [1]:
import numpy as np

In [2]:
test_example = np.array([[1,2,3],[4.5,5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
print(test_example[0][0])
print(test_example[0,0])

1
1


In [4]:
test_example[0,2] = 5
test_example

array([[1, 2, 5],
       [4, 5, 6]])

#### slicing

In [5]:
test_example = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]], int)
test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [6]:
test_example[0:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [7]:
test_example[:,1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [8]:
test_example = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
test_example[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [9]:
test_example[1][1:3]

array([7, 8])

In [10]:
test_example[1:3]

array([[ 6,  7,  8,  9, 10]])

In [11]:
a = np.arange(100).reshape(10,10)
a[:,-1].reshape(-1,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])