In [1]:
import numpy as np

### all & any

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a<0

array([False, False, False, False, False, False, False, False, False,
       False])

In [4]:
np.any(a>5), np.any(a<0)

(True, False)

In [5]:
np.all(a>5), np.all(a<10)

(False, True)

### comparison operation

In [6]:
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)
test_a > test_b

array([False,  True, False])

In [7]:
test_a == test_b

array([False, False, False])

In [8]:
(test_a > test_b).any()

True

In [9]:
a = np.array([1, 3, 0], float)
np.logical_and(a>0, a<3)

array([ True, False, False])

In [10]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [11]:
c = np.array([False, True, False])
np.logical_or(b,c)

array([ True,  True,  True])

### where

In [12]:
a = np.array([1,3,0], float)
a

array([1., 3., 0.])

In [13]:
np.where(a>0, 3, 2)

array([3, 3, 2])

In [14]:
a = np.arange(5,15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.where(a>10)

(array([6, 7, 8, 9]),)

In [16]:
# Nan: Not a Number
# Inf: Infinite
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [17]:
np.isfinite(a)

array([ True, False, False])

### argmax & argmin

In [18]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmin(a), np.argmax(a)

(0, 5)

In [19]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))